---
- name: Setting Up Repo Node
  hosts: repo
  become: true
  gather_facts: false
  ignore_errors: true

  vars:
    - password: password

  tasks:

    - name: Setting Hostname
      ansible.builtin.hostname:
        name: repo.ansi.example.com

    - name: Creating User Account
      ansible.builtin.user:
        name: user
        shell: /bin/bash
        groups: wheel
        append: true
        password: "{{ password | password_hash('sha512') }}"

    - name: Changing Root Password
      ansible.builtin.user:
        name: root
        password: "{{ password | password_hash('sha512') }}"

    - name: Disabling services
      ansible.posix.selinux:
        state: disabled

    - name: Building Host File
      ansible.builtin.copy:
        dest: /etc/hosts
        src: "{{ playbook_dir }}/files/hosts"
        mode: "0644"
        owner: root
        group: root
        force: true

    - name: Enabling services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - httpd
        - firewalld

    - name: Starting Firewalld
      ansible.posix.firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      with_items:
        - http
        - https
        - ntp
        - dns
        - kerberos
        - ldap
        - ldaps
        - ftp

    - name: Reloading Firewall
      ansible.builtin.service:
        name: firewalld
        state: restarted

    - name: Enabling IPV6
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '0'
        state: present
        reload: true
      with_items:
        - net.ipv6.conf.lo.disable_ipv6
        - net.ipv6.conf.all.disable_ipv6

    - name: Creating Welcome Message
      ansible.builtin.file:
        path: /etc/profile.d/welcome.sh
        state: touch
        mode: "0755"

    - name: Fixing SELinux Contexts
      ansible.builtin.command: restorecon -Rv /var/www/html

    - name: Building Welcome Message
      ansible.builtin.blockinfile:
        dest: /etc/profile.d/welcome.sh
        block: |
          #!/bin/bash
          #
          echo -e '
          #           _          _           _         _
          #          /\ \       /\ \        /\ \      /\ \
          #         /  \ \     /  \ \      /  \ \    /  \ \
          #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \
          #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \
          #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\
          #     / / /__\/ // /____/\   / / /__\/ / / /   / / /
          #    / / /_____// /\____\/  / / /_____/ / /   / / /
          #   / / /\ \ \ / / /______ / / /     / / /___/ / /
          #  / / /  \ \ / / /_______/ / /     / / /____\/ /
          #  \/_/    \_\\/__________\/_/      \/_________/
          '"#
          # Why are you here? You should be working on the system hosts...
          # Anyway, try not to reboot me or bad stuff can happen.
          #
          # You are logged into \"`hostname`\" as the \"`whoami`\" account.
          # This system is running `cat /etc/redhat-release`
          #
          "
