---
- hosts: all
  become: yes
  tasks:

    - name: Template
      template:
        src: server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        mode: 0600
        setype: net_conf_t
      when: "'database' in group_names"

